SETUP

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('dirty_cafe_sales.csv')
df.describe()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
count,10000,9667,9862,9821,9827,7421,6735,9841
unique,10000,10,7,8,19,5,4,367
top,TXN_1961373,Juice,5,3.0,6.0,Digital Wallet,Takeaway,UNKNOWN
freq,1,1171,2013,2429,979,2291,3022,159

In [3]:
df.isna().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

In [4]:
df['Payment Method'].value_counts()

Payment Method
Digital Wallet    2291
Credit Card       2273
Cash              2258
ERROR              306
UNKNOWN            293
Name: count, dtype: int64

In [5]:
df['Payment Method'] = df['Payment Method'].replace(['UNKNOWN','ERROR'], np.nan)

In [6]:
df['Payment Method'].isna().sum()

np.int64(3178)

In [7]:
df.set_index('Transaction ID')

,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
Transaction ID,,,,,,,
TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
TXN_7034554,Salad,2,5.0,10.0,NaN,UNKNOWN,2023-04-27
TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...
TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [8]:
df_filtered = df.drop(columns = ['Transaction ID'])
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

In [9]:
print(df_filtered.apply(lambda col: col.unique()))

Item                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    [Coffee, Cake, Cookie, Salad, Smoothie, UNKNOWN, Sandwich, nan, ERROR, Juice, Tea]
Quantity                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              [2, 4, 5, 3, 1, ERROR, UNKNOWN, nan]
Price Per Unit                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         [2.0, 3.0, 1.0, 5.0, 4.0, 1.5, nan, ERROR, UNKNOWN]
Total Spent                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               [4.0, 12.0, ERROR, 10.0, 20.0, 9.0, 16.0, 15.0, 25.0, 8.0, 5.0, 3.0, 6.0, nan, UNKNOWN, 2.0, 1.0, 7.5, 4.5, 1.5]
Payment Method                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    [Credit Card, Cash, nan, Digital Wallet]
Location                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         [Takeaway, In-store, UNKNOWN, nan, ERROR]
Transaction Date    [2023-09-08, 2023-05-16, 2023-07-19, 2023-04-27, 2023-06-11, 2023-03-31, 2023-10-06, 2023-10-28, 2023-07-28, 2023-12-31, 2023-11-07, ERROR, 2023-05-03, 2023-06-01, 2023-03-21, 2023-11-15, 2023-06-10, 2023-02-24, 2023-03-25, 2023-01-15, 2023-04-04, 2023-03-30, 2023-12-01, 2023-09-18, 2023-06-03, 2023-12-13, 2023-04-20, 2023-04-10, 2023-03-11, 2023-06-02, 2023-11-06, 2023-08-15, 2023-10-09, 2023-05-28, 2023-07-17, 2023-04-29, 2023-06-08, 2023-06-29, 2023-04-17, 2023-12-22, 2023-01-10, 2023-10-02, 2023-02-23, 2023-03-22, 2023-11-03, 2023-03-02, 2023-06-26, 2023-05-02, 2023-09-05, 2023-01-08, 2023-03-15, 2023-11-25, 2023-12-05, 2023-03-19, 2023-06-27, 2023-04-19, 2023-10-07, 2023-09-30, 2023-05-27, 2023-11-18, 2023-10-20, 2023-10-03, 2023-10-27, 2023-04-06, 2023-01-31, 2023-12-08, 2023-06-19, 2023-12-14, 2023-07-16, 2023-02-22, nan, 2023-06-15, 2023-12-09, 2023-04-18, 2023-10-29, 2023-04-30, 2023-04-02, 2023-05-24, 2023-03-12, 2023-08-16, 2023-09-10, 2023-03-07, 2023-08-07, 2023-08-20, 2023-04-15, 2023-07-25, 2023-10-30, 2023-12-15, 2023-02-25, 2023-04-03, 2023-10-08, 2023-12-28, 2023-08-30, 2023-02-03, 2023-09-12, 2023-05-04, 2023-02-21, UNKNOWN, 2023-03-16, 2023-02-06, ...]
dtype: object

In [10]:
df = df.replace(['UNKNOWN','ERROR'], np.nan)

In [11]:
unique_per_column = {col: df[col].unique() for col in df.columns if col != 'Transaction ID'}
unique_per_column

{'Item': <ArrowStringArray>
 [  'Coffee',     'Cake',   'Cookie',    'Salad', 'Smoothie',        nan,
  'Sandwich',    'Juice',      'Tea']
 Length: 9, dtype: str,
 'Quantity': <ArrowStringArray>
 ['2', '4', '5', '3', '1', nan]
 Length: 6, dtype: str,
 'Price Per Unit': <ArrowStringArray>
 ['2.0', '3.0', '1.0', '5.0', '4.0', '1.5', nan]
 Length: 7, dtype: str,
 'Total Spent': <ArrowStringArray>
 [ '4.0', '12.0',    nan, '10.0', '20.0',  '9.0', '16.0', '15.0', '25.0',
   '8.0',  '5.0',  '3.0',  '6.0',  '2.0',  '1.0',  '7.5',  '4.5',  '1.5']
 Length: 18, dtype: str,
 'Payment Method': <ArrowStringArray>
 ['Credit Card', 'Cash', nan, 'Digital Wallet']
 Length: 4, dtype: str,
 'Location': <ArrowStringArray>
 ['Takeaway', 'In-store', nan]
 Length: 3, dtype: str,
 'Transaction Date': <ArrowStringArray>
 ['2023-09-08', '2023-05-16', '2023-07-19', '2023-04-27', '2023-06-11',
  '2023-03-31', '2023-10-06', '2023-10-28', '2023-07-28', '2023-12-31',
  ...
  '2023-08-01', '2023-01-20', '2023-11-11', '2023-02-13', '2023-07-30',
  '2023-02-17', '2023-05-20', '2023-11-05', '2023-03-27', '2023-07-03']
 Length: 366, dtype: str}

In [12]:
pd.reset_option('display.max_rows')
pd.reset_option('display.max_columns')
pd.reset_option('display.max_colwidth')

In [13]:
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,NaN,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,NaN,NaN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [14]:
float_columns = ['Quantity','Price Per Unit', 'Total Spent']
df[float_columns] = df[float_columns].astype(float)

In [15]:
df['Total Spent'].isna().sum()

np.int64(502)

In [16]:
df['Total Spent'] = df['Total Spent'].fillna((df['Quantity'] * df['Price Per Unit']))

In [17]:
df['Total Spent'].isna().sum()

np.int64(40)

In [18]:
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,4.0,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.0,NaN,NaN,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [19]:
df['Price Per Unit'].isna().sum()

np.int64(533)

In [20]:
df['Price Per Unit'] = df['Price Per Unit'].fillna(df['Total Spent'] / df['Quantity'])

In [21]:
df['Price Per Unit'].isna().sum()

np.int64(38)

In [22]:
df['Quantity'].isna().sum()

np.int64(479)

In [23]:
df['Quantity'] = df['Quantity'].fillna(df['Total Spent'] / df['Price Per Unit'])

In [24]:
df['Quantity'].isna().sum()

np.int64(38)

In [25]:
df.dropna(subset=['Quantity','Total Spent', 'Price Per Unit'], inplace=True)

In [26]:
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,4.0,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.0,NaN,NaN,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2.0,2.0,4.0,NaN,NaN,2023-08-30
9996,TXN_9659401,NaN,3.0,1.0,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4.0,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3.0,1.0,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3.0,4.0,12.0,Cash,In-store,2023-11-07

In [27]:
df['Transaction Date'] = pd.to_datetime(df['Transaction Date'])

In [28]:
df['Transaction Date'].isna().sum()
df.shape

(9942, 8)

In [29]:
sorted_df = df.sort_values('Transaction ID')
sorted_df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
2987,TXN_1000555,Tea,1.0,1.5,1.5,Credit Card,In-store,2023-10-19
115,TXN_1001832,Salad,2.0,5.0,10.0,Cash,Takeaway,NaT
418,TXN_1002457,Cookie,5.0,1.0,5.0,Digital Wallet,Takeaway,2023-09-29
3417,TXN_1003246,Juice,2.0,3.0,6.0,NaN,NaN,2023-02-15
4366,TXN_1004184,Smoothie,1.0,4.0,4.0,Credit Card,In-store,2023-05-18
...,...,...,...,...,...,...,...,...
1389,TXN_9996968,Sandwich,1.0,4.0,4.0,Cash,In-store,2023-10-14
7964,TXN_9997263,Cookie,2.0,1.0,2.0,NaN,NaN,2023-03-05
4304,TXN_9997620,Cookie,2.0,1.0,2.0,Cash,NaN,2023-12-11
98,TXN_9999113,Juice,4.0,3.0,12.0,Cash,Takeaway,2023-05-27
5037,TXN_9999124,Juice,2.0,3.0,6.0,Digital Wallet,Takeaway,NaT

In [30]:
sorted_df['Transaction Date'] = sorted_df['Transaction Date'].ffill(limit=1)
sorted_df['Transaction Date'].isna().sum()

np.int64(32)

In [31]:
sorted_df['Transaction Date'].unique()

<DatetimeArray>
['2023-10-19 00:00:00', '2023-09-29 00:00:00', '2023-02-15 00:00:00',
 '2023-05-18 00:00:00', '2023-10-28 00:00:00', '2023-11-04 00:00:00',
 '2023-06-03 00:00:00', '2023-04-21 00:00:00', '2023-11-30 00:00:00',
 '2023-08-28 00:00:00',
 ...
 '2023-08-20 00:00:00', '2023-05-13 00:00:00', '2023-04-03 00:00:00',
 '2023-05-06 00:00:00', '2023-04-16 00:00:00', '2023-02-12 00:00:00',
 '2023-06-25 00:00:00', '2023-07-09 00:00:00', '2023-10-31 00:00:00',
 '2023-05-04 00:00:00']
Length: 366, dtype: datetime64[us]

In [32]:
sorted_df['Transaction Date'] = sorted_df['Transaction Date'].bfill(limit=1)
sorted_df['Item'].isna().sum()

np.int64(963)

In [33]:
price_map = {2.00:'Coffee', 1.50:'Tea', 1.00: 'Cookie', 5.00: 'Salad'}
missing_items = sorted_df['Price Per Unit'].map(price_map)
sorted_df['Item'] = sorted_df['Item'].fillna(missing_items)
sorted_df['Item'].isna().sum()
sorted_df['Item'].unique()

<ArrowStringArray>
[     'Tea',    'Salad',   'Cookie',    'Juice', 'Smoothie',   'Coffee',
     'Cake',        nan, 'Sandwich']
Length: 9, dtype: str

In [34]:
mapping = ['Sandwich','Smoothie']
price_4_filter = (sorted_df['Item'].isna()) & (sorted_df['Price Per Unit'] == 4.00)
missing_count_4 = price_4_filter.sum()
if missing_count_4 > 0:
    sorted_df.loc[price_4_filter, 'Item'] = np.random.choice(mapping, size = missing_count_4, p = [0.5, 0.5])
sorted_df['Item'].isna().sum()

np.int64(247)

In [35]:
mapping_3 = ['Cake','Juice']
price_3_filter = (sorted_df['Item'].isna()) & (sorted_df['Price Per Unit'] == 3.00)
missing_count_3 = price_3_filter.sum()
if missing_count_3 > 0:
    sorted_df.loc[price_3_filter, 'Item'] = np.random.choice(mapping_3, size = missing_count_3, p = [0.5, 0.5])
sorted_df['Item'].isna().sum()

np.int64(0)

In [37]:
sorted_df.head(3)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
2987,TXN_1000555,Tea,1.0,1.5,1.5,Credit Card,In-store,2023-10-19
115,TXN_1001832,Salad,2.0,5.0,10.0,Cash,Takeaway,2023-10-19
418,TXN_1002457,Cookie,5.0,1.0,5.0,Digital Wallet,Takeaway,2023-09-29

In [45]:
sorted_df['Payment Method'].isna().sum()
missing_payment_filter = sorted_df['Payment Method'].isna()
sorted_df.loc[missing_payment_filter,'Payment Method'] = sorted_df['Payment Method'].dropna().sample(sorted_df['Payment Method'].isna().sum()).values
sorted_df['Payment Method'].isna().sum()

np.int64(0)

In [47]:
sorted_df['Location'].isna().sum()
missing_location_filter = sorted_df['Location'].isna()
sorted_df.loc[missing_location_filter,'Location'] = sorted_df['Location'].dropna().sample(sorted_df['Location'].isna().sum()).values

In [48]:
sorted_df.isna().sum()

Transaction ID      0
Item                0
Quantity            0
Price Per Unit      0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
dtype: int64

In [49]:
sorted_df.to_csv('cleaned_cafe_sales.csv')