SETUP

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('dirty_cafe_sales.csv')

In [3]:
df.isna().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

In [4]:
df['Payment Method'].value_counts()

Payment Method
Digital Wallet    2291
Credit Card       2273
Cash              2258
ERROR              306
UNKNOWN            293
Name: count, dtype: int64

In [5]:
df['Payment Method'] = df['Payment Method'].replace(['UNKNOWN','ERROR'], np.nan)

In [22]:
df['Payment Method'].isna().sum()

np.int64(3178)

In [8]:
df.set_index('Transaction ID')

,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
Transaction ID,,,,,,,
TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
TXN_7034554,Salad,2,5.0,10.0,NaN,UNKNOWN,2023-04-27
TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...
TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [19]:
df_filtered = df.drop(columns = ['Transaction ID'])
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

In [20]:
print(df_filtered.apply(lambda col: col.unique()))

Item                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    [Coffee, Cake, Cookie, Salad, Smoothie, UNKNOWN, Sandwich, nan, ERROR, Juice, Tea]
Quantity                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              [2, 4, 5, 3, 1, ERROR, UNKNOWN, nan]
Price Per Unit                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         [2.0, 3.0, 1.0, 5.0, 4.0, 1.5, nan, ERROR, UNKNOWN]
Total Spent                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               [4.0, 12.0, ERROR, 10.0, 20.0, 9.0, 16.0, 15.0, 25.0, 8.0, 5.0, 3.0, 6.0, nan, UNKNOWN, 2.0, 1.0, 7.5, 4.5, 1.5]
Payment Method                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    [Credit Card, Cash, nan, Digital Wallet]
Location                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         [Takeaway, In-store, UNKNOWN, nan, ERROR]
Transaction Date    [2023-09-08, 2023-05-16, 2023-07-19, 2023-04-27, 2023-06-11, 2023-03-31, 2023-10-06, 2023-10-28, 2023-07-28, 2023-12-31, 2023-11-07, ERROR, 2023-05-03, 2023-06-01, 2023-03-21, 2023-11-15, 2023-06-10, 2023-02-24, 2023-03-25, 2023-01-15, 2023-04-04, 2023-03-30, 2023-12-01, 2023-09-18, 2023-06-03, 2023-12-13, 2023-04-20, 2023-04-10, 2023-03-11, 2023-06-02, 2023-11-06, 2023-08-15, 2023-10-09, 2023-05-28, 2023-07-17, 2023-04-29, 2023-06-08, 2023-06-29, 2023-04-17, 2023-12-22, 2023-01-10, 2023-10-02, 2023-02-23, 2023-03-22, 2023-11-03, 2023-03-02, 2023-06-26, 2023-05-02, 2023-09-05, 2023-01-08, 2023-03-15, 2023-11-25, 2023-12-05, 2023-03-19, 2023-06-27, 2023-04-19, 2023-10-07, 2023-09-30, 2023-05-27, 2023-11-18, 2023-10-20, 2023-10-03, 2023-10-27, 2023-04-06, 2023-01-31, 2023-12-08, 2023-06-19, 2023-12-14, 2023-07-16, 2023-02-22, nan, 2023-06-15, 2023-12-09, 2023-04-18, 2023-10-29, 2023-04-30, 2023-04-02, 2023-05-24, 2023-03-12, 2023-08-16, 2023-09-10, 2023-03-07, 2023-08-07, 2023-08-20, 2023-04-15, 2023-07-25, 2023-10-30, 2023-12-15, 2023-02-25, 2023-04-03, 2023-10-08, 2023-12-28, 2023-08-30, 2023-02-03, 2023-09-12, 2023-05-04, 2023-02-21, UNKNOWN, 2023-03-16, 2023-02-06, ...]
dtype: object

In [26]:
df = df.replace(['UNKNOWN','ERROR'], np.nan)

In [29]:
unique_per_column = {col: df[col].unique() for col in df.columns if col != 'Transaction ID'}
unique_per_column

{'Item': <StringArray>
 [  'Coffee',     'Cake',   'Cookie',    'Salad', 'Smoothie',        nan,
  'Sandwich',    'Juice',      'Tea']
 Length: 9, dtype: str,
 'Quantity': <StringArray>
 ['2', '4', '5', '3', '1', nan]
 Length: 6, dtype: str,
 'Price Per Unit': <StringArray>
 ['2.0', '3.0', '1.0', '5.0', '4.0', '1.5', nan]
 Length: 7, dtype: str,
 'Total Spent': <StringArray>
 [ '4.0', '12.0',    nan, '10.0', '20.0',  '9.0', '16.0', '15.0', '25.0',
   '8.0',  '5.0',  '3.0',  '6.0',  '2.0',  '1.0',  '7.5',  '4.5',  '1.5']
 Length: 18, dtype: str,
 'Payment Method': <StringArray>
 ['Credit Card', 'Cash', nan, 'Digital Wallet']
 Length: 4, dtype: str,
 'Location': <StringArray>
 ['Takeaway', 'In-store', nan]
 Length: 3, dtype: str,
 'Transaction Date': <StringArray>
 ['2023-09-08', '2023-05-16', '2023-07-19', '2023-04-27', '2023-06-11',
  '2023-03-31', '2023-10-06', '2023-10-28', '2023-07-28', '2023-12-31',
  ...
  '2023-08-01', '2023-01-20', '2023-11-11', '2023-02-13', '2023-07-30',
  '2023-02-17', '2023-05-20', '2023-11-05', '2023-03-27', '2023-07-03']
 Length: 366, dtype: str}

In [30]:
pd.reset_option('display.max_rows')
pd.reset_option('display.max_columns')
pd.reset_option('display.max_colwidth')

In [31]:
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,NaN,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,NaN,NaN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11